// TODO: 对应中文
export const SIGNUP = {
  enterprise_name: DataTypes.STRING,
  enterprose_cell: DataTypes.STRING,
  password: DataTypes.STRING,
  validate_code: DataTypes.STRING,
  graph_validate_code: DataTypes.STRING,
  cell_validate_code: DataTypes.STRING,
  invite_cell_code: DataTypes.STRING,
  certificate_3_in_1: DataTypes.STRING,
  organization_type: DataTypes.STRING,
  unified_social_credit_code: DataTypes.STRING,
  business_license_validity_period: DataTypes.STRING,
  account_approval_no: DataTypes.STRING,
  legal_representative_name: DataTypes.STRING,
  legal_representative_certificate_no: DataTypes.STRING,
  legal_representative_certificate_no_expiry_date: DataTypes.STRING,
  operator_name: DataTypes.STRING,
  operator_certificate_no: DataTypes.STRING,
  operator_certificate_expiry_date: DataTypes.STRING,
  operator_email: DataTypes.STRING,
  registry_address: DataTypes.STRING,
  contact_address: DataTypes.STRING,
  enterprise_fullName: DataTypes.STRING,
  TIN: DataTypes.STRING,
  address: DataTypes.STRING,
  cell: DataTypes.STRING,
  bank: DataTypes.STRING,
  bank_account: DataTypes.STRING,
  fullName: DataTypes.STRING,
  receiver_name: DataTypes.STRING,
  receiver_cell: DataTypes.STRING,
};