query get_post {
  post(id: 1) {
    id
    title
    body
  }
}

query get_user {
  user(id: 1) {
    id
    username
    email
    address {
      geo {
        lat
        lng
      }
    }
  }
}

query get_user_post {
  user(id: 1) {
    posts {
      data {
        id
        title
      }
    }
  }
}

query get_photo_album($id: ID!) {
  photo(id: $id) {
    album {
      id
      title
      user {
        id
      }
    }
  }
}

query get_all_posts($options: PageQueryOptions) {
  posts(options: $options) {
    data {
      id
      title
    }
    meta {
      totalCount
    }
  }
}

mutation($input: CreatePostInput!) {
  createPost(input: $input) {
    id
    title
    body
  }
}

mutation update_post($id: ID!, $input: UpdatePostInput!) {
  updatePost(id: $id, input: $input) {
    id
    body
  }
}

mutation delete_post($id: ID!) {
  deletePost(id: $id)
}
