export { default as OpenWeatherMap } from './openweathermap'
export { default as GoogleMap } from './googlemap'
export { default as NewsApi } from './newsapi'
export { default as InfiniteLoop } from './infiniteLoop'
export { default as GNews } from './gnews'
